const translations = {
  en: {
    brand_title: "MIAT Mongolian Airlines",
    brand_sub: "",
    nav_home: "Home",
    nav_flight: "Flight",
    nav_esim: "eSIM",
    nav_video: "Sponsored",
    nav_voo: "VOO",
    nav_about: "About",
    status_text: "MIAT inflight",
    aircraft_tag: "Aircraft",
    aircraft_overview: "Overview",
    aircraft_engine_label: "Engines",
    aircraft_manu_label: "Manufacturer",
    spec_engines: "Engines",
    spec_tyre: "Tyre",
    spec_range: "Range",
    spec_speed: "Cruise",
    badge: "Welcome aboard",
    hero_title_prefix: "Your friend in the sky.",
    hero_lead: "The journey can be long, but it doesn't have to be boring.",
    demo_desc: "Demo version — full content coming soon.",
    about_title: "About MIAT",
    about_desc: "MIAT inflight portal with flight info, eSIM, and entertainment access.",
    about_points_title: "Built for the cabin",
    cta_voo: "Open VOO",
    cta_flight: "Flight details",
    tab_voo: "VOO",
    tab_movies: "Movies",
    tab_music: "Music",
    tab_kids: "Kids",
    section_new: "New release",
    section_popular: "Popular",
    feature_badge: "New",
    cta_watch: "Watch now",
    cta_details: "Details",
    label_all: "All",
    tag_qr: "QR onboarding in seconds",
    tag_lang: "MN and EN ready",
    tag_server: "Onboard content server",
    flight_greeting: "Flight summary",
    flight_aircraft: "MIAT - Boeing 737-800",
    flight_destination: "Очих газар: ICN (Сөүл)",
    flight_time_left_title: "Үлдсэн хугацаа",
    flight_time_left_value: "1ц 10м үлдлээ",
    flight_destination: "Destination: ICN (Seoul)",
    flight_time_left_title: "Time left",
    flight_time_left_value: "1h 10m remaining",
    seat_pill: "Seat 6E | Economy",
    label_altitude: "Altitude",
    label_flightno: "Flight number",
    label_temp: "Temperature",
    label_speed: "Speed",
    label_remaining_km: "Remaining",
    label_destination: "Destination",
    label_distance: "Route",
    label_eta: "ETA",
    route_start: "ULN 14:10",
    route_mid: "1h 10m remaining",
    route_end: "ICN 15:35",
    quick_title: "Other services",
    quick_sub: "Tap to open",
    quick_flight: "Flight info",
    quick_flight_desc: "Live status, altitude, ETA",
    quick_flight_tag: "ULN -> ICN",
    quick_esim: "eSIM offers",
    quick_esim_desc: "Stay connected after landing",
    quick_esim_tag: "3GB - 5 days",
    quick_video: "Sponsored video",
    quick_video_desc: "Partner highlight reel",
    quick_video_tag: "Now playing",
    quick_voo: "VOO streaming",
    quick_voo_desc: "Movies, music, originals",
    quick_voo_cta: "Launch VOO",
    tile_voo: "Movie",
    tile_sonsy: "Music",
    tile_need: "Need help",
    tile_flight: "Flight info",
    tile_xplore: "Xplore",
    tile_about_desc: "Company info",
    back_home: "Back",
    cta_xplore: "Xplore",
    help_title: "Need help",
    help_lead: "Quick services and buttons for your journey.",
    help_mobilife_title: "MobiLife",
    help_mobilife_desc: "Travel insurance service.",
    help_esim_title: "eSIM",
    help_esim_desc: "Fast data access abroad.",
    help_skyshop_title: "Sky Shop",
    help_skyshop_desc: "Onboard exclusive items and prices.",
    help_chat_title: "Chat & Assistance",
    help_chat_desc: "Request help from your seat.",
    help_cta_open: "Open",
    help_cta_soon: "Coming soon",
    section_flight_title: "Flight info",
    section_flight_sub: "Live status",
    flight_status_title: "Status",
    flight_status_desc: "On time with smooth skies.",
    flight_status_route: "ULN -> ICN",
    flight_status_alt: "Altitude 35,500 ft",
    flight_cabin_title: "Cabin services",
    flight_cabin_meals: "Meals: service in 20 minutes",
    flight_cabin_power: "Seat power: rows 10-30",
    flight_cabin_support: "Support: call cabin crew via seat panel",
    flight_weather_title: "Destination weather",
    flight_weather_desc: "Clear skies expected at arrival.",
    flight_weather_wind: "Wind: light breeze",
    flight_weather_temp: "Temperature: 6 C",
    section_esim_title: "eSIM offers",
    section_esim_sub: "Stay connected after landing",
    esim_how_title: "How it works",
    esim_how_1: "1. Pick your region and data size",
    esim_how_2: "2. Pay securely in flight",
    esim_how_3: "3. Activate on arrival",
    esim_plans_title: "Recommended plans",
    esim_plan_1: "East Asia: 3GB - 5 days",
    esim_plan_2: "Global: 8GB - 20 days",
    esim_plan_3: "Premium: 15GB - 30 days",
    esim_support_title: "Support",
    esim_support_desc: "Scan the QR on your seat pocket for step by step setup.",
    esim_support_tag: "24/7 chat in VOO",
    section_video_title: "Sponsored video",
    section_video_sub: "Partner highlight reel",
    video_title: "Discover Mongolia",
    video_desc: "Short film featuring the steppe, sky, and city lights.",
    video_note: "Demo only - full playback onboard.",
    video_partner_title: "Featured partner",
    video_partner_desc: "Route specific brand stories with QR follow ups.",
    video_partner_tag: "Sponsored",
    section_voo_title: "VOO access",
    section_voo_sub: "Main experience for passengers",
    voo_title_prefix: "Make the cabin feel like cinema with",
    voo_desc:
      "This demo redirects to the public VOO site. In flight, the VOO tab opens the onboard content server with movies, series, music, and originals.",
    voo_cta: "Launch VOO",
    voo_back: "Back to Flight",
    voo_inside_title: "What is inside VOO",
    voo_inside_1: "Originals, films, and series",
    voo_inside_2: "Mongolian music and audio",
    voo_inside_3: "Kids content and safe mode",
    footer_left: "MIAT inflight portal - powered by VOO",
    footer_right: "Need help? Ask the cabin crew."
  },
  mn: {
    brand_title: "МИАТ Монголын Агаарын Тээвэр",
    brand_sub: "",
    nav_home: "Нүүр",
    nav_flight: "Нислэг",
    nav_esim: "eSIM",
    nav_video: "Ивээн тэтгэсэн",
    nav_voo: "VOO",
    nav_about: "Бидний тухай",
    status_text: "MIAT нислэг",
    aircraft_tag: "Нисэх онгоц",
    aircraft_overview: "Тойм",
    aircraft_engine_label: "Хөдөлгүүр",
    aircraft_manu_label: "Үйлдвэрлэгч",
    spec_engines: "Хөдөлгүүр",
    spec_tyre: "Дугуй",
    spec_range: "Хүрээ",
    spec_speed: "Нислэгийн хурд",
    badge: "Тавтай морил",
    hero_title_prefix: "Тэнгэрт таны найз.",
    hero_lead: "Аяллын цаг урт байж болно, харин уйтгартай байх албагүй.",
    demo_desc: "Демо хувилбар — бүрэн контент удахгүй нэмэгдэнэ.",
    about_title: "МИАТ-ийн тухай",
    about_desc: "МИАТ-ийн нислэгийн портал. Нислэгийн мэдээлэл, eSIM, зугаацах контентыг нэг төвд нэгтгэнэ.",
    about_points_title: "Онгоцонд зориулсан",
    cta_voo: "VOO нээх",
    cta_flight: "Нислэгийн мэдээлэл",
    tab_voo: "VOO",
    tab_movies: "Кино",
    tab_music: "Хөгжим",
    tab_kids: "Хүүхэд",
    section_new: "Шинэ",
    section_popular: "Түгээмэл",
    feature_badge: "Шинэ",
    cta_watch: "Шууд үзэх",
    cta_details: "Дэлгэрэнгүй",
    label_all: "Бүгд",
    tag_qr: "QR-ээр 1 агшинд",
    tag_lang: "MN болон EN",
    tag_server: "Онгоцны дотоод сервер",
    flight_greeting: "Нислэгийн товч",
    flight_aircraft: "MIAT - Boeing 737-800",
    seat_pill: "Суудал 6E | Энгийн",
    label_altitude: "Өндөр",
    label_flightno: "Нислэгийн дугаар",
    label_temp: "Температур",
    label_speed: "Хурд",
    label_remaining_km: "Үлдсэн зай",
    label_destination: "Очих газар",
    label_distance: "Маршрут",
    label_eta: "Ирэх цаг",
    route_start: "УЛН 14:10",
    route_mid: "1ц 10м үлдлээ",
    route_end: "ИЧН 15:35",
    quick_title: "Бусад үйлчилгээ",
    quick_sub: "Дарж нээнэ үү",
    quick_flight: "Нислэгийн мэдээлэл",
    quick_flight_desc: "Төлөв, өндөр, ирэх цаг",
    quick_flight_tag: "УЛН -> ИЧН",
    quick_esim: "eSIM саналууд",
    quick_esim_desc: "Буусны дараа холбоо",
    quick_esim_tag: "3ГБ - 5 өдөр",
    quick_video: "Ивээн тэтгэсэн видео",
    quick_video_desc: "Онцлох түншийн бичлэг",
    quick_video_tag: "Одоо тоглож байна",
    quick_voo: "VOO стриминг",
    quick_voo_desc: "Кино, хөгжим, контент",
    quick_voo_cta: "VOO нээх",
    tile_voo: "Кино",
    tile_sonsy: "Хөгжим",
    tile_need: "Танд хэрэгтэй",
    tile_flight: "Нислэгийн мэдээлэл",
    tile_xplore: "Xplore",
    tile_about_desc: "Компанийн мэдээлэл",
    back_home: "Буцах",
    cta_xplore: "Xplore",
    help_title: "Танд хэрэгтэй",
    help_lead: "Аяллын үеэр хэрэгтэй үйлчилгээ, санал болон тусламжийн товчлуурууд.",
    help_mobilife_title: "MobiLife",
    help_mobilife_desc: "Аяллын даатгалын шийдэл.",
    help_esim_title: "eSIM",
    help_esim_desc: "Гадаадад дата ашиглах хурдан шийдэл.",
    help_skyshop_title: "Sky Shop",
    help_skyshop_desc: "Онгоцны онцгой бүтээгдэхүүн, үнэ мэдээлэл.",
    help_chat_title: "Чат & Тусламж",
    help_chat_desc: "Суудлаасаа тусламж хүсэх товч.",
    help_cta_open: "Нээх",
    help_cta_soon: "Удахгүй",
    section_flight_title: "Нислэгийн мэдээлэл",
    section_flight_sub: "Амьд мэдээлэл",
    flight_status_title: "Төлөв",
    flight_status_desc: "Тайван нисэж байна.",
    flight_status_route: "УЛН -> ИЧН",
    flight_status_alt: "Өндөр 35,500 ft",
    flight_cabin_title: "Кабины үйлчилгээ",
    flight_cabin_meals: "Хоол: 20 минутын дараа",
    flight_cabin_power: "Суудлын цахилгаан: 10-30 эгнээ",
    flight_cabin_support: "Тусламж: суудлын самбар",
    flight_weather_title: "Очих хотын цаг агаар",
    flight_weather_desc: "Цэлмэг байх төлөвтэй.",
    flight_weather_wind: "Салхи: намуухан",
    flight_weather_temp: "Температур: 6 C",
    section_esim_title: "eSIM саналууд",
    section_esim_sub: "Буусны дараа холбоотой бай",
    esim_how_title: "Хэрхэн ажиллах вэ",
    esim_how_1: "1. Бүс нутаг ба дата сонгох",
    esim_how_2: "2. Нислэгийн үеэр төлөх",
    esim_how_3: "3. Буусны дараа идэвхжүүлэх",
    esim_plans_title: "Санал болгож буй багцууд",
    esim_plan_1: "Зүүн Ази: 3ГБ - 5 өдөр",
    esim_plan_2: "Дэлхий: 8ГБ - 20 өдөр",
    esim_plan_3: "Премиум: 15ГБ - 30 өдөр",
    esim_support_title: "Тусламж",
    esim_support_desc: "Суудлын халаас дахь QR-ыг уншуулж заавар авна.",
    esim_support_tag: "VOO дотор 24/7 чат",
    section_video_title: "Ивээн тэтгэсэн видео",
    section_video_sub: "Онцлох түншийн үзүүлэн",
    video_title: "Монголыг нээцгээе",
    video_desc: "Тал нутаг, тэнгэр, хотын гэрэл.",
    video_note: "Демо хувилбар - бүрэн үзвэр онгоцонд.",
    video_partner_title: "Онцлох түнш",
    video_partner_desc: "Маршруттай уялдсан брэндийн түүхүүд.",
    video_partner_tag: "Ивээн тэтгэсэн",
    section_voo_title: "VOO хандалт",
    section_voo_sub: "Зорчигчийн үндсэн туршлага",
    voo_title_prefix: "Кабиныг кино театр болгох",
    voo_desc:
      "Энэ демо нь VOO-ийн олон нийтэд нээлттэй сайтад шилжинэ. Нислэгийн үед VOO таб нь дотоод серверийг нээж кино, цуврал, хөгжим, оригинал контентыг үзүүлнэ.",
    voo_cta: "VOO нээх",
    voo_back: "Нислэг рүү буцах",
    voo_inside_title: "VOO дотор",
    voo_inside_1: "Оригинал, кино, цуврал",
    voo_inside_2: "Монгол хөгжим, аудио",
    voo_inside_3: "Хүүхдийн контент, safe mode",
    footer_left: "МИАТ нислэгийн портал - VOO-оор дэмжигдсэн",
    footer_right: "Тусламж хэрэгтэй бол стюардыг дуудна уу."
  }
};

const applyLang = (lang) => {
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    const value = translations[lang][key];
    if (value) {
      el.textContent = value;
    }
  });
};

const setActiveLang = (lang) => {
  document.querySelectorAll("[data-lang]").forEach((b) => {
    b.classList.toggle("active", b.getAttribute("data-lang") === lang);
  });
  applyLang(lang);
  localStorage.setItem("voo_lang", lang);
};

const savedLang = localStorage.getItem("voo_lang") || "mn";
setActiveLang(savedLang);

document.querySelectorAll("[data-lang]").forEach((btn) => {
  btn.addEventListener("click", () => {
    setActiveLang(btn.getAttribute("data-lang"));
  });
});


